language: php

sudo: false

php:
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL=5.8.*
    - LARAVEL=dev-master

matrix:
  fast_finish: true
  allow_failures:
    - env: LARAVEL=dev-master

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
