language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: SETUP=nightly
    - php: 7.2
    - php: 7.2
      env: SETUP=nightly
    - php: 7.3
    - php: 7.3
      env: SETUP=nightly
  allow_failures:
    - php: 7.1
      env: SETUP=nightly
    - php: 7.2
      env: SETUP=nightly
    - php: 7.3
      env: SETUP=nightly

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'nightly' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi

script: vendor/bin/phpunit --verbose
