name: tests

  on: [push]

  jobs:
    test:

      runs-on: ubuntu-latest
      strategy:
        fail-fast: true
        matrix:
          php: [7.2, 7.3, 7.4]
          laravel: [6.*, 7.*]

      name: P${{ matrix.php }} - L${{ matrix.laravel }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Cache dependencies
          uses: actions/cache@v1
          with:
            path: ~/.composer/cache/files
            key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

        - name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: ${{ matrix.php }}
            extension-csv: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
            coverage: none

        - name: Install dependencies
          run: composer require "illuminate/contracts=${{ matrix.laravel }}" --prefer-dist --no-interaction --no-suggest

        - name: Execute tests
          run: vendor/bin/phpunit --verbose
